apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworldidp
  description: Find your internal developer portal
spec:
  type: Service
  lifecycle: production
  owner: idp-team
catalog:
  rules:
    - allow: [Component, API, Location, Template]

  locations:
    - type: url
      target: https://github.com/sekharpe/helloworldidp/blob/master/helloworld.yaml
      rules:
        - allow: []
